### ISSUE TITLE
[Discussion] About switcher

### ISSUE THREAD

**Issue by nyngwang** [GnikDroy/projections.nvim#16]
I think I just figured out why things didn't work as expected. If `switcher.switch` is designed to be called inside the `callback` of any autocmd related to `cwd`-change, then we should remove line 19 in my perspective.

Let's emulate the process:

1. Say we just open neovim so `VimEnter` happen, and let's say the `cwd` is `A`.
2. In the callback, `switcher.switch(vim.loop.cwd())` will receive `A`. It then checks for unsaved files first(and no since it's `VimEnter`), and change `cwd` to `A` when it run through line 19. Finally, it cleans things up before calling `Session.restore()`. So that line 19 is actually redundant as long as you pass `cwd` into `switcher.switch`...

Furthermore:

1. As a user I would expect the process of storing/restoring sessions can be done automatically upon any of my call to change `cwd`. To achieve this, you should make use of `autocmd`.
2. In my current understanding: when you were designing `switcher.switch`, I guess that you were thinking about "OK so users are recommended to always use this function to change between projects". But with line 19 in the code, `switcher.switch` can only be put in the callback of `xxxPre` event. If it is put in the `xxxPost`,`xxxChanged`, then `vim.fn.chdir(spath)` will always change from `B` to `B`.

Am I wrong in this analysis? 

https://github.com/GnikDroy/projections.nvim/blob/be100ad3540952542c2a1135f39cddea8a1a00de/lua/projections/switcher.lua#L18-L25

```lua
vim.api.nvim_create_autocmd({ "VimEnter" }, {
    callback = function()
        if vim.fn.argc() == 0 then switcher.switch(vim.loop.cwd()) end
    end,
})
```

**Comment by GnikDroy** [comment]
I can also use `noautocmd` for that line though... Would that be okay?

**Comment by GnikDroy** [comment]
We now use noautocmd for `cd` from 07540a1c089785cafe8690e096447cf1a166c497, which should have been the behaviour before.

This enables you to use DirChanged event without triggering the autocmd multiple times. Alternatively, depending on use case, you can use SessionLoad events.
