### ISSUE TITLE
Extension is not loaded after calling other pickers

### ISSUE THREAD

**Issue by richban** [GnikDroy/projections.nvim#17]
I am not so sure why but when I open neovim and run `checkhealth telescope` the extension is loaded, however when I execute my mappings, it always  de-loads the extensions.

<img width="915" alt="image" src="https://user-images.githubusercontent.com/6967088/207592490-79a88dc9-5012-4878-8303-2f4f65183b5a.png">
 
Here is my `telescope` config https://github.com/richban/dotfiles/tree/master/dotfiles/config/nvim/lua/rb/telescope

**Comment by GnikDroy** [comment]
The config is huge. 

I would need a few things to diagnose this:

1) A minimal config containing only telescope, projections (and maybe packer).
2) Exact steps needed to reproduce.

**Comment by richban** [comment]
Closing this as it was a problem in my configs. Work as intended.
