### ISSUE TITLE
[BUG]: Bad argument to ipairs

### ISSUE THREAD

**Issue by eccentric-j** [GnikDroy/projections.nvim#19]
# Reproduction

1. Install projections
2. Setup the first recommended recipe. Bind <leader>pp to run `Telescope projections` (see below)
3. Restart neovim (I'm using Neovide), and open a project by pressing `<leader>pp`
4. Select a project
5. Open a new tab `:tabe`
6. Press `<leader>pp` again

## Expected

The project selector Telescope UI renders allowing me to select a project.

## Actual

When pressing `<leader>pp` it throws the following error, preventing the telescope UI from rendering:

```
E5108: Error executing lua: Vim:Error executing Lua callback: ...acker/opt/projections.nvim/lua/projections/workspace.lua:84: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
	[C]: in function 'ipairs'
	...acker/opt/projections.nvim/lua/projections/workspace.lua:84: in function 'is_project'
	...acker/opt/projections.nvim/lua/projections/workspace.lua:56: in function 'projects'
	...ojections.nvim/lua/telescope/_extensions/projections.lua:13: in function 'project_finder'
	...ojections.nvim/lua/telescope/_extensions/projections.lua:41: in function <...ojections.nvim/lua/telescope/_extensions/projections.lua:36>
	...pack/packer/opt/telescope.nvim/lua/telescope/command.lua:193: in function 'run_command'
	...pack/packer/opt/telescope.nvim/lua/telescope/command.lua:253: in function 'load_command'
	...site/pack/packer/opt/telescope.nvim/plugin/telescope.lua:108: in function <...site/pack/packer/opt/telescope.nvim/plugin/telescope.lua:107>
	[C]: at 0x01059656e6
stack traceback:
	[C]: at 0x01059656e6
```

This plugin seems super helpful, please let me know if any more info would help for debugging.

### Recipe Used

```lua
use({
    "gnikdroy/projections.nvim",
    config = function()
        require("projections").setup({})

        -- Bind <leader>fp to Telescope projections
        require('telescope').load_extension('projections')
        vim.keymap.set("n", "<leader>pp", function() vim.cmd("Telescope projections") end)

        -- Autostore session on VimExit
        local Session = require("projections.session")
        vim.api.nvim_create_autocmd({ 'VimLeavePre' }, {
            callback = function() Session.store(vim.loop.cwd()) end,
        })

        -- Switch to project if vim was started in a project dir
        local switcher = require("projections.switcher")
        vim.api.nvim_create_autocmd({ "VimEnter" }, {
            callback = function()
                if vim.fn.argc() == 0 then switcher.switch(vim.loop.cwd()) end
            end,
        })
    end
})
```

**Comment by GnikDroy** [comment]
`patterns` seems to be nil. Weird. I will respond after testing

**Comment by GnikDroy** [comment]
Okay so with your config, I don't get an error. 

The error is at this line
```lua
for _, pattern in ipairs(self.patterns) do
```

`self.patterns` MUST be a list like table, but it got `nil` instead.

`self.patterns` is the patterns for a workspace. You have configured no workspaces in setup. So, the only other place they could be setup is `stdpath('data') .. 'projections_workspaces.json'`

Please attach the contents of that file here.

**Comment by eccentric-j** [comment]
Ah that may have been the issue then! My first attempt I had:

```lua
{
  workspaces={“~/projects”, {“.git”}}
}
```

Instead of

```lua
{
  workspaces={{“~/projects”, {“.git”}}}
}
```

**Comment by GnikDroy** [comment]
I recommend the `AddWorkspace` command to do this. The JSON file format is not explained for exactly this reason.

```lua
local Workspace = require("projections.workspace")
-- Add workspace command
vim.api.nvim_create_user_command("AddWorkspace", function() 
    Workspace.add(vim.loop.cwd()) 
end, {})
```
Instead, 
1. Remove current json file
2. Open `nvim`.
3. `:cd` to workspace.
4. `:AddWorkspace`

**Comment by eccentric-j** [comment]
I can see where that could work. Alternatively, would you be open to a PR to add more validation to the config?

**Comment by GnikDroy** [comment]
Sure. I should validate values in setup() and deserialize(). That would be great.

**Comment by GnikDroy** [comment]
It is also probably worthwhile to clean the way projection serializes to the json file and expose that information in the README. I'm currently using the default neovim serializer for the `workspace` table, which might not be ideal for human consumption.
