### ISSUE TITLE
[feat] Bring back lua patterns

### ISSUE THREAD

**Issue by GnikDroy** [GnikDroy/projections.nvim#22]
Bring back support for lua patterns. This provides more flexibility, now that use cases have been reported.

I should also notify users of this breaking change, via the commit message, which packer picks up.

Also, a `vim.notify` call for people who don't have this type of function built into their package manager. I could do this for example by searching through patterns in all workspaces and recognizing common errors like `.git` which should be `^%.git$` and so on. This also enables projections to automatically correct common errors. This "incorrect usage of pattern" checker will be present for a couple of months, at the very least - potentially forever.

**Comment by eccentric-j** [comment]
At first I thought that would be really helpful. Then once I got my config working, switched it to:

```fennel
(projections.setup
  {:workspaces [["~/projects"   [".git"]]
                ["~/dotfiles"   []]]})
```

Including all the subdirs in dotfiles is actually the behavior I wanted where as initially I was trying to include all subdirs with a .org file in them. It may be helpful to others to support patterns but at least for my use-case the above behavior is preferred.

**Comment by GnikDroy** [comment]
Perfect. I will keep the branch, and not merge anything then. Will only merge this if someone requests it.
