### ISSUE TITLE
[bug] Projection does not store session, even when calling .store(vim.loop.cwd()) manually.

### ISSUE THREAD

**Issue by Gremious** [GnikDroy/projections.nvim#24]
**Expected vs Actual behavior**

Running `Telescope projections` finds my projects just fine.
However, entering a project does not restore a session, as it seem that projections is just not storing any session file.
I have specified a custom sessions_directory just for testing this, and ether via autocommands or via `:lua require("projections.session").store(vim.loop.cwd())`, no session file gets created/stored. The folder does get created, but it stays empty.

I don't know if/where you guys store any logs, please do tell if I can share more information. 

**Environment information**
- Neovim version:
```
NVIM v0.9.0-dev-417+g1390e97c2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az153-379
```
- Operating system: Windows 11 (MSYS_NT-10.0-22621 PC-Name 3.3.6-341.x86_64 2022-09-05 20:28 UTC x86_64 Msys)
- Projections branch/commit hash: #[d27a16a](https://github.com/GnikDroy/projections.nvim/commit/d27a16a13c70a64d29b899b698842bfac99307be)
- Projections config:
```lua 
use("gnikdroy/projections.nvim")

require("projections").setup({
	workspaces = {
		"C:/Users/Gremious/Projects/Programming/Gremy/dev",
		"C:/Users/Gremious/Projects/dev",
	},
	sessions_directory = "ProjectionsSessions"
})

telescope.load_extension("projections")
```

- Projections workspace file (find this at `stdpath('data') .. 'projections_workspaces.json'`: 
```lua

```

- Result of `ls -lah` from projection sessions folder (find this at `stdpath('cache') .. 'projections_sessions/'` . Remove personal information as needed.
```lua
total 0
drwxrwxrwx 1 gremious gremious 4.0K Dec 24 19:32 .
drwxrwxrwx 1 gremious gremious 4.0K Dec 24 19:32 ..
```

Result of `set sessionoptions?`: `sessionoptions=blank,buffers,curdir,folds,help,tabpages,winsize,terminal,localoptions,winpos`

**To Reproduce**
1. Change config to more easily accessible folder, e.g. sessions_directory = "ProjectionsSessions"
2. Switch to a project, e.g. via telescope
3. run `:lua require("projections.session").store(vim.loop.cwd())`
4. Inspect the ProjectionsSessions folder in your project, it will be empty?

**Comment by GnikDroy** [comment]
store() function returns a status value. 
Can you check what it returns?

**Comment by GnikDroy** [comment]
I can reproduce this, so I will investigate further. Can you try with an absolute path for `sessions_directory`, instead?

**Comment by Gremious** [comment]
I have changed `sessions_directory` to `"C:\\Users\\Gremious\\ProjectionsSesssions"`

`:lua= require("projections.session").store(vim.loop.cwd())` creates said directory, returns "`false`", no session file inside

`:lua= require("projections.session").info(vim.loop.cwd())` returns `nil`

`:lua= vim.loop.cwd()` returns `"C:\\Users\\Gremious\\Projects\\Programming\\gremy\\dev\\dungeon-gen"` (which is the directory with .git, yeah)

---

More update:

I call `nvim` in terminal, in project directory.

I do `:lua= require("projections.session").store(vim.loop.cwd())` - it returns false, no session file

I then do `Telescope projections` and switch to any other project - calling `store` now returns true and creates a session file. This is also true if i switch back to the original project. It just works from now on.

This is *not* true if I open nvim a directory up, and then move into the project (`:pwd` displays the project, still doesn't save)

(I do not lazy load projections)

**Comment by GnikDroy** [comment]
I think I have figured it out (thankfully, because `Session.info()` returned `nil`). It might be related to the behavior of file names on Windows.

Cases don't matter in windows, unlike Linux. `tExT.txt` is same as `text.txt` or `TEXT.TXT`

Hence, this is wrong in windows.
https://github.com/GnikDroy/projections.nvim/blob/67f80a2a44bb425849f966db57a53415d478c5ae/lua/projections/path.lua#L10-L12

**Comment by GnikDroy** [comment]
Hopefully, fe34d98df4210365f62fef8a2aaeed0d9456b56f fixed your issue.

**Comment by Gremious** [comment]
Sorry missed the message, but yes - everything seems to work correctly now! Thank you very much for the fast fix!

As a sidenote, I think it's cool that you can make `sessions_directory` a relative directory and it just uses the project folder, it means that you can potentially commit your session and switch machines more seamlessly (I used to do that with my IDE between home and work back when when I did not use vim).

**Comment by GnikDroy** [comment]
@Gremious It is possible to support relative `sessions_directory`, but that would mean one additional feature that I need to maintain :)

There are other ways to achieve this without using a relative `sessions_directory`.

```lua
local function copy_session()
    local Session = require("projections.session")
    local session = Session.info(vim.loop.cwd())
    if session then
        local dest = vim.loop.cwd() .. "/.session.vim"
        vim.fn.system(string.format("cp %s %s", tostring(session.path), dest))
        return vim.v.shell_error == 0
    end
    return false
end
```


Whenever you want to commit, just call this function.

You can bind to a keybinding, a user command, maybe run this function automatically when you launch fugitive? On store_hooks.post maybe?

Actually, running this on `store_hooks.post` might make it completely automatic.

Have not tested any of the code, so apologies if it has some errors.

**Comment by Gremious** [comment]
Oh that's really nice - thank you!
