### ISSUE TITLE
[bug] Syntax highlight disabled when reopening the session even saving session with 'localoptions'

### ISSUE THREAD

**Issue by JohnsonLee-debug** [GnikDroy/projections.nvim#31]
**Basic checklist**
- [x] I have read the README
- [x] I have read the wiki
- [x] I have read `:h session`, `:h mksession`, and `:h sessionoptions`
- [x] I have searched through existing/closed issues
- [x] I have checked if the recommended config has changed, and if that solves my issue.

**Expected vs Actual behavior**

Syntax highlight doesn't work if i start vim in a project root. However it could work correctly if i switch to the project manually. 

[![asciicast](https://asciinema.org/a/Q1DQBjYBBV6PjvGJOvHNDHSk9.svg)](https://asciinema.org/a/Q1DQBjYBBV6PjvGJOvHNDHSk9)

**Environment information**
- Neovim version:  v0.9.0-dev
- Operating system: Ubuntu 20.04
- Projections branch/commit hash: 6820ad90343b5ec78f236bbe0e13d9c8078a0c48 
- Projections config:
```lua 
require("projections").setup({
		patterns = { ".git", ".svn", ".hg", ".root" },
	})

require('telescope').load_extension('projections')

-- Autostore session on VimExit
local Session = require("projections.session")
vim.api.nvim_create_autocmd({ 'VimLeavePre' }, {
		callback = function()
			Session.store(vim.loop.cwd())
		end,
})

-- Switch to project if vim was started in a project dir
local switcher = require("projections.switcher")
vim.api.nvim_create_autocmd({ "VimEnter" }, {
		callback = function()
				if vim.fn.argc() == 0 then switcher.switch(vim.loop.cwd()) end
		end,
})

local Session = require("projections.session")
vim.api.nvim_create_user_command("StoreProjectSession", function()
    Session.store(vim.loop.cwd())
end, {})

vim.api.nvim_create_user_command("RestoreProjectSession", function()
    Session.restore(vim.loop.cwd())
end, {})

local Workspace = require("projections.workspace")
-- Add workspace command
vim.api.nvim_create_user_command("AddWorkspace", function() 
    Workspace.add(vim.loop.cwd()) 
end, {})
```

- Projections workspace file (find this at `stdpath('data') .. 'projections_workspaces.json'`: 
```json
[{"path":"\/home\/johnsonlee\/.config","patterns":[".git",".svn",".hg",".root"]},{"path":"\/home\/johnsonlee\/SRC\/neovim_plugins","patterns":[".git",".svn",".hg",".root"]}]
```

- Result of `ls -lah` from projection sessions folder (find this at `stdpath('cache') .. 'projections_sessions/'` . Remove personal information as needed.
```
Permissions Size User       Date Modified Name
.rw-r--r--  1.1k johnsonlee 21 Feb 00:39  doom_11075730298852069376.vim
.rw-r--r--  1.4k johnsonlee 21 Feb 02:54  nvim_11075730298852069376.vim
.rw-r--r--  1.5k johnsonlee 21 Feb 02:00  nvim_11075730298852069376.vim.bak
.rw-r--r--  1.1k johnsonlee 21 Feb 02:24  projections.nvim_1931065204751606784.vim
```

**To Reproduce**
1. Configure projections like above
2. Add a workspace, open a project
3. quit nvim and start nvim under the project root

**Comment by GnikDroy** [comment]
A few more things I need before working on this issue.

1) Are you using treesitter? If so, is treesitter lazy loaded?
2) If you open nvim in project dir and then do `:e`, is syntax highlighting reenabled?
3) Can you link the `nvim_.......vim` file present in `projection_sessions/`

**Comment by JohnsonLee-debug** [comment]
1. I'm using treesittter, but it's not lazy loaded
2. Yes, it will
3. [nvim_11075730298852069376.vim](https://paste.ofcode.org/S33mDt3veUu6WkTBLFDMqD)

**Comment by GnikDroy** [comment]
I believe this is a treesitter and/or package manager issue.

1. Does manually loading the session file work? For example, with `nvim -S nvim_....vim`? If manually loading the session file also doesn't work, then this is not a projection's issue.

2. If `1.` was an issue you can also try something like `nvim file_1.ext file_2.ext` and it won't work. Therefore, further proving my point.

I cannot seem to reproduce this, so it is likely a package manager issue. Do you use `lazy.nvim` by any chance?

**Comment by JohnsonLee-debug** [comment]
No I use packer.

**Comment by JohnsonLee-debug** [comment]
I'm trying to fix that.

**Comment by GnikDroy** [comment]
Could you figure out if it was projection's fault?

**Comment by JohnsonLee-debug** [comment]
I think `projections.nvim` does nothing wrong. `nvim -S session_file.vim` don't work as well.
