### ISSUE TITLE
[feat] wildcard patterns 

### ISSUE THREAD

**Issue by airtonix** [GnikDroy/projections.nvim#33]
**Is your feature request related to a problem? Please describe.**

- I'm using [Lazy](https://github.com/folke/lazy.nvim)
- I just want to specify a wildcard pattern for projection to search for project directories.

```lua
return {
    "gnikdroy/projections.nvim",
    config = function()
        require("projections").setup({
            workspaces = {
                { "~/Projects/**/*", { ".git" }}
            }
        })
}
```
**Describe the solution you'd like**

this 
```lua
 workspaces = {
                { "~/Projects/**/*", { ".git" }}
            }
```
should match all of 🫠: 

```
~/
  Projects/
    Mine/
      Github/
        AProject/  🫠
           .git/
           package.json
           ...
        SomeProject/ 🫠
           .git/
           package.json
           ...
        SomeProject-Worktrees/
          SomeProject-A/ 🫠
             .git/
             package.json 
          SomeProject-B/ 🫠
             .git/
             package.json
          SomeProject-C/ 🫠
             .git/
             package.json
           ...
        AnotherProject/ 🫠
           .git/
           package.json
           ...
```

**If appropriate, have you considered any alternatives?**

🙈🙉🙊

**Additional context**

🙈🙉🙊

**Comment by GnikDroy** [comment]
I was hoping the ability to add multiple workspaces would partially ease the pain.

Why not add `Github/` and `Github/Some-Project-Worktrees/` to `workspaces.json` with the `:AddWorkspace` command (or via the config)? Are there a lot of folders like `Github/` or `Github/Some-Project-Worktrees/` to make this infeasible?

---

I would like to avoid projections having to "search" for projects too much. If I make `~/Projects/**/*` possible, surely `~/Projects/**/**/**/*` should also work. That would mean I have to be a lot more careful with performance. Currently, projections is "instantaneous".

While it is possible to create something like `depth=` which searches for patterns multiple levels deep, I believe I would need to rely on something like `ripgrep` to make this performant. 

For example, imagine a `node_modules/` in `Projects/Mine/A` `Projects/Mine/B` folder. We would have to be:
1) a lot more performant
2) include an option to "exclude" directories from search, or respect a project's `.gitignore` (both available from ripgrep)

To me, the solution to this issue boils down to:
1) Disallow complex project searches. 🙈🙉🙊
2) Rely on `ripgrep` existing on the user's system. 🫡
3) Implement functionality from ripgrep yourself 😨


I would like to avoid having any dependencies.

If you have any ideas on how to make this possible with a relatively simple codebase, I am open to suggestions.

**Comment by airtonix** [comment]
Yep, i see. 

It'l be up to me to : 


```lua
return {
    "gnikdroy/projections.nvim",
    config = function()
        require("projections").setup({
            workspaces = functionThatBuildsListOfWorkSpaces("~/Projects/**/*")
        })
}
```
