### ISSUE TITLE
[bug] breaks with yadm alt directories

### ISSUE THREAD

**Issue by ibrokemypie** [GnikDroy/projections.nvim#36]
**Basic checklist**
- [x] I have read the README
- [x] I have read the wiki
- [x] I have read `:h session`, `:h mksession`, and `:h sessionoptions`
- [x] I have searched through existing/closed issues
- [x] I have checked if the recommended config has changed, and if that solves my issue.

**Expected vs Actual behavior**
When trying to go to a project that is a yadm managed alt directory I get a big error rather than changing to the project. I believe this is due to the hashes in the filename which yadm uses to denote files for specific system configurations.
```
E5108: Error executing lua vim/_editor.lua:0: nvim_exec2(): Vim(cd):E500: Evaluates to an empty string: noautocmd cd /home/noodle/.config/yadm/alt/.config/waybar##os.Linux           
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        .../nvim/lazy/projections.nvim/lua/projections/switcher.lua:19: in function 'switch'
        ...ojections.nvim/lua/telescope/_extensions/projections.lua:68: in function 'action'
        ...ojections.nvim/lua/telescope/_extensions/projections.lua:72: in function 'run_replace_or_original'
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:352: in function 'execute_keymap'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

**Environment information**
- Neovim version: 0.9.0
- Operating system: arch linux
- Projections branch/commit hash:
- Projections config:
```lua 
return {
	"gnikdroy/projections.nvim",
	event = "VeryLazy",
	opts = {
		workspaces = {
			"~/git",
			{ "~/.config", {} },
			{ "~/.config/yadm/alt/.config", {} },
		},
	},
	config = function(_, opts)
		require("projections").setup(opts)

		-- Autostore session on VimExit
		local Session = require("projections.session")
		vim.api.nvim_create_autocmd({ "VimLeavePre" }, {
			callback = function()
				Session.store(vim.loop.cwd())
			end,
		})

		-- Switch to project if vim was started in a project dir
		local switcher = require("projections.switcher")
		vim.api.nvim_create_autocmd({ "VimEnter" }, {
			callback = function()
				if vim.fn.argc() == 0 then
					switcher.switch(vim.loop.cwd())
				end
			end,
		})

		vim.opt.sessionoptions:append("localoptions") -- Save localoptions to session file
	end,
}

```

- Projections workspace file (find this at `stdpath('data') .. 'projections_workspaces.json'`: 
```lua
-- contents of file here (keep empty if none)
```

- Result of `ls -lah` from projection sessions folder (find this at `stdpath('cache') .. 'projections_sessions/'` . Remove personal information as needed.
```lua
total 60K
drwxr-xr-x 2 noodle noodle 4.0K May 16 13:46 .
drwxr-xr-x 6 noodle noodle 4.0K May 16 10:43 ..
-rw-r--r-- 1 noodle noodle  11K May 16 13:44 api_8460989840036524032.vim
-rw-r--r-- 1 noodle noodle 9.7K May 16 13:44 nvim_12491412145565761536.vim
```

- Result of `tree -a -L 2` from every configured workspace (both config and workspace json file). Remove personal and unnecessary information as needed.
```lua
thisll be huge and don't think its needed, can add if required
```

**To Reproduce**
1. Create some config specific alts in yadm
2. Add yadm alts dir as a workspace
3. Use the telescope picker to try and open one of these alts

**Comment by GnikDroy** [comment]
Apologies for replying late. 

I can verify the issue.

Something like this will not work from neovim either.

```nvim
:cd /home/noodle/.config/yadm/alt/.config/waybar##os.Linux
```

The "#" character is problematic.

It should be a relatively easy fix. I will look at this later today.

**Comment by GnikDroy** [comment]
Hopefully d41bbf6 fixed your issue. Feel free to reopen if issue persists.
