### ISSUE TITLE
[feat] Update directory on neotree

### ISSUE THREAD

**Issue by snikoletopoulos** [GnikDroy/projections.nvim#37]
**Is your feature request related to a problem? Please describe.**
When changing projects, neotree displays the previous project making it feel less like a project change

**Describe the solution you'd like**
When i change projects I would like for neotree to change the directory as well

**If appropriate, have you considered any alternatives?**
I don't know if there are. We could have a discussion tab to look into if there is an other way before making an issue

**Comment by GnikDroy** [comment]
See https://github.com/GnikDroy/projections.nvim#-interaction-with-plugins

The example shows a way to close Neotree while switching sessions.

Alternatively, you can use a post restore hook to "refresh" neo-tree (assuming the only problem is "neotree displays the previous project")

```lua
require("projections").setup({
    ...
    restore_hooks = { post = function()
        -- code to "refresh" neotree
    end },
})
```

If this is not exactly what you want, I would need an exact description of the behavior you want.

But in general, a combination of store_hooks (pre/post) and restore_hooks (pre/post) handle this.

**Comment by GnikDroy** [comment]
Feel free to reopen if you have further issues.

**Comment by jonestristand** [comment]
This only works if I have previously opened the project and saved a session in it. If I open a project, open nvim-tree (or presumably neo-tree), then open a new project that I have never opened before, nvim-tree will not update to the new directory. Any way to add a hook for just opening a project?
