### ISSUE TITLE
[Cross-Plugin] Both `store_hooks`, `restore_hooks` cannot be used to close `neo-tree`.

### ISSUE THREAD

**Issue by nyngwang** [GnikDroy/projections.nvim#4]
As title.

**Comment by nyngwang** [comment]
The problem was solved by removing all usage of `switcher`s.

**Comment by GnikDroy** [comment]
@nyngwang Removing all usage of switcher has its own sets of problems. 

I am currently looking at this issue. I do not use neo-tree so I'm a bit slow. :) 
I have managed to close neo-tree on prestore hooks. I am checking on ways to restore it as well.

**Comment by GnikDroy** [comment]
@nyngwang The README is updated. 
See [Interactions with other plugins](https://github.com/GnikDroy/projections.nvim#interactions-with-other-plugins). I will take a look at restoring neotree as well.

**Comment by nyngwang** [comment]
@GnikDroy Hi, thanks for you taking care of my issues (and sorry about my rudeness of writing them in a hurry). Let me clarify something you just replied.

> [...] I will take a look at restoring neotree as well.

No! You don't need to restore neo-tree buffer. Regarding to what you have said about the switcher, I only need your help on fixing the switcher not properly closing those pre/post hooks.

**Comment by GnikDroy** [comment]
@nyngwang Don't worry. You were not not rude. :D Always happy to help. If my recent commits have not solved your issue, then feel free to provide additional details. If they have solved your problem, then you can close this issue.

**Comment by nyngwang** [comment]
@GnikDroy I have edited my comment, you might want to take a look again. Thanks for you kindness :)

**Comment by nyngwang** [comment]
When my plugin (actually just a extension using your plugin and another one) is done, I will definitely let more people know your plugin :)

**Comment by nyngwang** [comment]
@GnikDroy

> [...] If my recent commits have not solved your issue, then feel free to provide additional details.

It seems that you just did that :) I see no problem currently!
