### ISSUE TITLE
[API request] Could you provide an API for extending `store_hooks`/`restore_hooks` on the run?

### ISSUE THREAD

**Issue by nyngwang** [GnikDroy/projections.nvim#5]
As title. I need to append more hooks after the `setup` of projections.nvim has been called. Is this possible?

That is, I want to achieve:

1. When users are setting the config of projections.nvim, they don't need to care about whether they have installed the extension or not. So they can basically setup projections.nvim like they never use any extension. (separation of concern.)
2. When users are setting the config of extensions of projections.nvim, they just put the related config on the extension's `setup`, not on the one of projections.nvim.

On the other hand, I should say any usage of `autocmd` is dangerous but usually it's not the business of plugin authors: the users should take care of it themselves as long as no conflicts are introduced. E.g. my extension will add some `autocmd`s but if these `autocmd`s cause some problems/conflicts with those one recommended in `projections.nvim` README.md then I should fix them.

**Comment by GnikDroy** [comment]
Actually, you can always access and override `projections` config.
```lua
local config = require("projections.config").config
```
This will give you the config table. 

So if you want to hook into `store_hook`, which the user has already configured in projection's config.
Do something like, 
```lua
local config = require("projections.config").config
-- Save function in a tmp variable first
local pre_store_hook_from_projections =  config.store_hooks.pre
-- Override 
config.store_hooks.pre = function(...)
    -- Do something here
    -- Call original prestore hook
    pre_store_hook_from_projections(...)
    -- Or do something here
end

```

**Please NOTE that this is possible only if you load your plugin after `projections`**

So, with packer, you would use `after = 'gnikdroy/projections.nvim'` while setting up your plugin.
It is possible to remove this requirement of `after`.
