### ISSUE TITLE
Many thanks for your creation of this plugin :)

### ISSUE THREAD

**Issue by nyngwang** [GnikDroy/projections.nvim#7]
I am always afraid of those projects with very long README.md explaining its complicated `setup`. For just "session restoring" there are already many existing plugins, but I should say none of them were doing a great job introducing their product to beginners. You did :) I finally can have a session management plugin I understood. Thanks for your adding it to https://github.com/rockerBOO/awesome-neovim!

**Comment by GnikDroy** [comment]
Thank you for your kind words. Glad it was of use to you.
