### ISSUE TITLE
Syntax highlight disabled when reopening the session

### ISSUE THREAD

**Issue by richban** [GnikDroy/projections.nvim#9]
When closing nvim and reopening nvim with the saved session the "active" buffer always gets opened without sytanx highlight and LSP.

Here is my config.

Awesome plugin! Want to make this work ;)  

https://user-images.githubusercontent.com/6967088/206322218-a5cfd756-1794-4c2f-b6d1-71cb941a9a79.mp4

**Comment by nyngwang** [comment]
Hi, the syntax highlighting is not enabled because you didn't store more info. into the session data. You can check this by this command on no-highlight files:

```
:set ft?
```

to enable highlighting, add this to your config(, assuming your config is written in Lua):


```lua
vim.opt.ssop:append({ 'localoptions' })
```

**Comment by GnikDroy** [comment]
@richban nyngwang is correct. You want to ensure localoptions is set in session options.

```lua
vim.opt.ssop:append({ 'localoptions' })
```
I will add this in a FAQ somewhere.

**Comment by richban** [comment]
Thanks both of you! Awesome plugin!
